base_url = "https://omnibor.io"
title = "OmniBOR"
compile_sass = false
build_search_index = true

[markdown]

highlight_code = true
highlight_theme = "ayu-light"

[extra]

nav = [
    { name = "Spec", url = "@/spec/_index.md", pill = "v0.1" },
    { name = "Docs", url = "@/docs/_index.md" },
    { sep = true },
    { name = "Blog", url = "@/blog/_index.md" },
    { name = "Project", url = "@/project.md" },
    { name = "Contribute", url = "@/contribute.md" },
    { sep = true },
    { icon = "github", url = "https://github.com/omnibor" },
]

footer = [
    [
        { name = "Spec", title = true },
        { name = "Stable", url = "@/spec/v0.1/_index.md", pill = "v0.1" },
        { name = "Latest", url = "https://github.com/omnibor/spec", external = true },
    ],
    [
        { name = "Tools", title = true },
        { name = "OmniBOR CLI", url = "https://github.com/omnibor/omnibor-rs/tree/main/omnibor-cli", external = true },
        { name = "bomsh", url = "https://github.com/omnibor/bomsh", external = true },
        { name = "jbor", url = "https://github.com/omnibor/jbor", external = true },
    ],
    [
        { name = "Libraries", title = true },
        { name = "Rust", url = "https://github.com/omnibor/omnibor-rs", external = true },
        { name = "Go", url = "https://github.com/omnibor/omnibor-go", external = true },
        { name = ".NET", url = "https://github.com/omnibor/omnibor-dotnet", external = true },
        { name = "Python", url = "https://github.com/omnibor/omnibor-py", external = true },
    ],
    [
        { name = "Docs", title = true },
        { name = "Artifact IDs", url = "@/docs/artifact-ids.md" },
        { name = "Input Manifests", url = "@/docs/input-manifests.md" },
        { name = "Glossary", url = "@/glossary/_index.md" },
        { name = "Resources", url = "@/resources/_index.md" },
    ],
    [
        { name = "Info", title = true },
        { name = "Contribute", url = "@/contribute.md" },
        { name = "Project", url = "@/project.md" },
    ],
    [
        { name = "Social", title = true },
        { name = "YouTube", url = "https://www.youtube.com/@omnibor", external = true },
        { name = "Twitter / X", url = "https://x.com/omnibor", external = true },
    ],
]
